// Generated by https://quicktype.io

export interface CommasUserDataDTO {
  id: number;
  auto_balance_period: number;
  auto_balance_portfolio_id: null;
  auto_balance_currency_change_limit: null;
  autobalance_enabled: boolean;
  is_locked: boolean;
  smart_trading_supported: boolean;
  smart_selling_supported: boolean;
  available_for_trading: any;
  stats_supported: boolean;
  trading_supported: boolean;
  market_buy_supported: boolean;
  market_sell_supported: boolean;
  conditional_buy_supported: boolean;
  bots_allowed: boolean;
  bots_ttp_allowed: boolean;
  bots_tsl_allowed: boolean;
  gordon_bots_available: boolean;
  multi_bots_allowed: boolean;
  created_at: string;
  updated_at: string;
  last_auto_balance: null;
  fast_convert_available: boolean;
  grid_bots_allowed: boolean;
  api_key_invalid: boolean;
  nomics_id: string;
  market_icon: string;
  supported_market_types: string[];
  api_key: string;
  name: string;
  auto_balance_method: null;
  auto_balance_error: null;
  lock_reason: null;
  btc_amount: string;
  usd_amount: string;
  day_profit_btc: string;
  day_profit_usd: string;
  day_profit_btc_percentage: string;
  day_profit_usd_percentage: string;
  btc_profit: string;
  usd_profit: string;
  usd_profit_percentage: string;
  btc_profit_percentage: string;
  total_btc_profit: string;
  total_usd_profit: string;
  pretty_display_type: string;
  exchange_name: string;
  market_code: string;
}

// export interface AvailableForTrading {}
